# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_shoplist.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 646)
        Form.setStyleSheet("background:white;\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 20, 131, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 10, 81, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(710, 30, 113, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 140, 77, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shop_name_1 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_1.setText("")
        self.shop_name_1.setObjectName("shop_name_1")
        self.verticalLayout_2.addWidget(self.shop_name_1)
        self.shop_name_2 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_2.setText("")
        self.shop_name_2.setObjectName("shop_name_2")
        self.verticalLayout_2.addWidget(self.shop_name_2)
        self.shop_name_3 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_3.setText("")
        self.shop_name_3.setObjectName("shop_name_3")
        self.verticalLayout_2.addWidget(self.shop_name_3)
        self.shop_name_5 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_5.setText("")
        self.shop_name_5.setObjectName("shop_name_5")
        self.verticalLayout_2.addWidget(self.shop_name_5)
        self.shop_name_4 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_4.setText("")
        self.shop_name_4.setObjectName("shop_name_4")
        self.verticalLayout_2.addWidget(self.shop_name_4)
        self.shop_name_6 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_6.setObjectName("shop_name_6")
        self.verticalLayout_2.addWidget(self.shop_name_6)
        self.shop_name_7 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_7.setObjectName("shop_name_7")
        self.verticalLayout_2.addWidget(self.shop_name_7)
        self.shop_name_8 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_8.setObjectName("shop_name_8")
        self.verticalLayout_2.addWidget(self.shop_name_8)
        self.shop_name_9 = QtWidgets.QLabel(self.layoutWidget)
        self.shop_name_9.setObjectName("shop_name_9")
        self.verticalLayout_2.addWidget(self.shop_name_9)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(300, 140, 62, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shop_id_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_1.setObjectName("shop_id_1")
        self.verticalLayout_3.addWidget(self.shop_id_1)
        self.shop_id_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_2.setObjectName("shop_id_2")
        self.verticalLayout_3.addWidget(self.shop_id_2)
        self.shop_id_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_3.setObjectName("shop_id_3")
        self.verticalLayout_3.addWidget(self.shop_id_3)
        self.shop_id_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_4.setObjectName("shop_id_4")
        self.verticalLayout_3.addWidget(self.shop_id_4)
        self.shop_id_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_5.setObjectName("shop_id_5")
        self.verticalLayout_3.addWidget(self.shop_id_5)
        self.shop_id_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_6.setObjectName("shop_id_6")
        self.verticalLayout_3.addWidget(self.shop_id_6)
        self.shop_id_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_7.setObjectName("shop_id_7")
        self.verticalLayout_3.addWidget(self.shop_id_7)
        self.shop_id_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_8.setObjectName("shop_id_8")
        self.verticalLayout_3.addWidget(self.shop_id_8)
        self.shop_id_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_9.setObjectName("shop_id_9")
        self.verticalLayout_3.addWidget(self.shop_id_9)
        self.shop_id_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.shop_id_10.setObjectName("shop_id_10")
        self.verticalLayout_3.addWidget(self.shop_id_10)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(420, 140, 62, 421))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.shop_owner_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_2.setObjectName("shop_owner_2")
        self.verticalLayout_4.addWidget(self.shop_owner_2)
        self.shop_owner_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_6.setObjectName("shop_owner_6")
        self.verticalLayout_4.addWidget(self.shop_owner_6)
        self.shop_owner_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_3.setObjectName("shop_owner_3")
        self.verticalLayout_4.addWidget(self.shop_owner_3)
        self.shop_owner_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_4.setObjectName("shop_owner_4")
        self.verticalLayout_4.addWidget(self.shop_owner_4)
        self.shop_owner_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_5.setObjectName("shop_owner_5")
        self.verticalLayout_4.addWidget(self.shop_owner_5)
        self.shop_owner_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_7.setObjectName("shop_owner_7")
        self.verticalLayout_4.addWidget(self.shop_owner_7)
        self.shop_owner_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_8.setObjectName("shop_owner_8")
        self.verticalLayout_4.addWidget(self.shop_owner_8)
        self.shop_owner_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_9.setObjectName("shop_owner_9")
        self.verticalLayout_4.addWidget(self.shop_owner_9)
        self.shop_owner_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_10.setObjectName("shop_owner_10")
        self.verticalLayout_4.addWidget(self.shop_owner_10)
        self.shop_owner_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.shop_owner_11.setObjectName("shop_owner_11")
        self.verticalLayout_4.addWidget(self.shop_owner_11)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(580, 140, 113, 431))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enter_shop_1 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_1.setObjectName("enter_shop_1")
        self.verticalLayout.addWidget(self.enter_shop_1)
        self.enter_shop_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_2.setObjectName("enter_shop_2")
        self.verticalLayout.addWidget(self.enter_shop_2)
        self.enter_shop_3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_3.setObjectName("enter_shop_3")
        self.verticalLayout.addWidget(self.enter_shop_3)
        self.enter_shop_4 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_4.setObjectName("enter_shop_4")
        self.verticalLayout.addWidget(self.enter_shop_4)
        self.enter_shop_5 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_5.setObjectName("enter_shop_5")
        self.verticalLayout.addWidget(self.enter_shop_5)
        self.enter_shop_6 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_6.setObjectName("enter_shop_6")
        self.verticalLayout.addWidget(self.enter_shop_6)
        self.enter_shop_7 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_7.setObjectName("enter_shop_7")
        self.verticalLayout.addWidget(self.enter_shop_7)
        self.enter_shop_8 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_8.setObjectName("enter_shop_8")
        self.verticalLayout.addWidget(self.enter_shop_8)
        self.enter_shop_9 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_9.setObjectName("enter_shop_9")
        self.verticalLayout.addWidget(self.enter_shop_9)
        self.enter_shop_10 = QtWidgets.QPushButton(self.layoutWidget3)
        self.enter_shop_10.setObjectName("enter_shop_10")
        self.verticalLayout.addWidget(self.enter_shop_10)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(190, 100, 331, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shop_name_head = QtWidgets.QLabel(self.widget)
        self.shop_name_head.setStyleSheet("font: 75 20pt \"Heiti SC\";")
        self.shop_name_head.setObjectName("shop_name_head")
        self.horizontalLayout.addWidget(self.shop_name_head)
        self.shop_id_head = QtWidgets.QLabel(self.widget)
        self.shop_id_head.setStyleSheet("font: 75 20pt \"Heiti SC\";")
        self.shop_id_head.setObjectName("shop_id_head")
        self.horizontalLayout.addWidget(self.shop_id_head)
        self.shop_owner_head = QtWidgets.QLabel(self.widget)
        self.shop_owner_head.setStyleSheet("font: 75 20pt \"Heiti SC\";")
        self.shop_owner_head.setObjectName("shop_owner_head")
        self.horizontalLayout.addWidget(self.shop_owner_head)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "选个心仪的店铺逛逛吧"))
        self.label_2.setText(_translate("Form", "user name"))
        self.label_3.setText(_translate("Form", "欢迎语"))
        self.pushButton_9.setText(_translate("Form", "谁在逛我的店铺"))
        self.shop_name_6.setText(_translate("Form", "TextLabel"))
        self.shop_name_7.setText(_translate("Form", "TextLabel"))
        self.shop_name_8.setText(_translate("Form", "TextLabel"))
        self.shop_name_9.setText(_translate("Form", "TextLabel"))
        self.shop_id_1.setText(_translate("Form", "TextLabel"))
        self.shop_id_2.setText(_translate("Form", "TextLabel"))
        self.shop_id_3.setText(_translate("Form", "TextLabel"))
        self.shop_id_4.setText(_translate("Form", "TextLabel"))
        self.shop_id_5.setText(_translate("Form", "TextLabel"))
        self.shop_id_6.setText(_translate("Form", "TextLabel"))
        self.shop_id_7.setText(_translate("Form", "TextLabel"))
        self.shop_id_8.setText(_translate("Form", "TextLabel"))
        self.shop_id_9.setText(_translate("Form", "TextLabel"))
        self.shop_id_10.setText(_translate("Form", "TextLabel"))
        self.shop_owner_2.setText(_translate("Form", "TextLabel"))
        self.shop_owner_6.setText(_translate("Form", "TextLabel"))
        self.shop_owner_3.setText(_translate("Form", "TextLabel"))
        self.shop_owner_4.setText(_translate("Form", "TextLabel"))
        self.shop_owner_5.setText(_translate("Form", "TextLabel"))
        self.shop_owner_7.setText(_translate("Form", "TextLabel"))
        self.shop_owner_8.setText(_translate("Form", "TextLabel"))
        self.shop_owner_9.setText(_translate("Form", "TextLabel"))
        self.shop_owner_10.setText(_translate("Form", "TextLabel"))
        self.shop_owner_11.setText(_translate("Form", "TextLabel"))
        self.enter_shop_1.setText(_translate("Form", "→"))
        self.enter_shop_2.setText(_translate("Form", "→"))
        self.enter_shop_3.setText(_translate("Form", "→"))
        self.enter_shop_4.setText(_translate("Form", "→"))
        self.enter_shop_5.setText(_translate("Form", "→"))
        self.enter_shop_6.setText(_translate("Form", "→"))
        self.enter_shop_7.setText(_translate("Form", "→"))
        self.enter_shop_8.setText(_translate("Form", "→"))
        self.enter_shop_9.setText(_translate("Form", "→"))
        self.enter_shop_10.setText(_translate("Form", "→"))
        self.shop_name_head.setText(_translate("Form", "店铺名"))
        self.shop_id_head.setText(_translate("Form", "店铺ID"))
        self.shop_owner_head.setText(_translate("Form", "拥有者"))

